#!/bin/bash

WINDOW="Counter-Strike: Global Offensive - OpenGL"
START_DELAY=20

#regex="tty.*(:[0-9])\)$"
#[[ $(who | grep tty) =~ $regex ]]
#export DISPLAY=${BASH_REMATCH[1]}

echo "Looking for window: $WINDOW"
if [[ ! $(wmctrl -l | grep "$WINDOW") ]]; then
  echo "Starting $WINDOW"
  xdg-open Steam://run/730
  echo "Waiting $START_DELAY seconds for program to start"

  while [ $START_DELAY -gt 1 ]; do
    START_DELAY=$(expr $(expr $START_DELAY / 2) + $(expr $START_DELAY % 2))
    echo "${START_DELAY}s....."
    sleep $START_DELAY
  done
  echo "Waiting for $WINDOW"
  while [[ ! $(wmctrl -l | grep "$WINDOW") ]]; do
    sleep 2
  done
fi

XDOWINDOW=$(xdotool search --name "$WINDOW")
echo "Minimizing $WINDOW"
xdotool windowminimize $XDOWINDOW

sleep 1

echo "Repositioning $WINDOW"
wmctrl -v -r "$WINDOW" -e 0,0,0,1600,1200

echo "Opening $WINDOW"
wmctrl -v -a "$WINDOW"

echo "Exiting in 5 seconds"
sleep 5

exit 0
